name: Java CI Win arm

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:

    runs-on: windows-11-arm

    steps:
      - uses: actions/checkout@v6

      - name: Set up Environment for Java 21
        shell: powershell
        run: |
          echo "JAVA_HOME=$env:JAVA_HOME_21_AARCH64" | Out-File -FilePath $env:GITHUB_ENV -Append                
          $javaBin = Join-Path $env:JAVA_HOME_21_AARCH64 "bin"
          echo "$javaBin" | Out-File -FilePath $env:GITHUB_PATH -Append

      - name: Build with Maven
        run: |
          java -version
          mvn -B package --file pom.xml
          ant -noinput -buildfile build.xml clean all